services:
  - type: web
    name: trello-clone-backend
    env: node
    plan: free
    rootDir: backend
    buildCommand: npm install && npx prisma db push && node prisma/seed.js
    startCommand: npm start
